### ISSUE TITLE
Create Tags Variable and Add to all Azure Resources

### ISSUE THREAD

**Issue by voor** [pivotal/paving#26]
Basically what is in AWS just for Azure.

```
variable "tags" {
  description = "Key/value tags to assign to all resources."
  default     = {}
  type        = map(string)
}
```

```
  tags = merge(
    var.tags,
    { account_for = "bosh" },
  )
```

Source: https://pivotal.slack.com/archives/C6B6HJ84V/p1579635111016500

**Comment by genevieve** [comment]
https://github.com/pivotal/paving/commit/d95a26d4f567864ffc376f38601a8c288240d5f4
https://github.com/pivotal/paving/commit/45a52429f71a94feed5342a065792a8e0bc0c730
https://github.com/pivotal/paving/commit/d7d810b9a72da8806a2eb1feb369dc92f195f91f

Forgot to tag the issue in the commits but this should do it!

**Comment by genevieve** [comment]
Note that not all the azure resources accept `tags` as argument.
