### ISSUE TITLE
Need a good way to document common modifications customers will encounter

### ISSUE THREAD

**Issue by voor** [pivotal/paving#38]
I have two forks right now, one that adds in Harbor and in Azure native Azure logging, then I have another using private DNS on Azure instead of public DNS (this will eventually be changed to use internal load balancers as well).  Wondering how to provide these as easily referable and accessible to future users.

**Comment by genevieve** [comment]
I'd like to reduce the amount of information in this repository for 3 reasons: (1) readability, (2) simplicity, and (3) maintenance. If it's possible to create a separate repository for additive templates or overrides that we can refer to from the readme in this repo, that would probably be best.
