### ISSUE TITLE
allow `paving` to remove resources for PAS/PKS

### ISSUE THREAD

**Issue by jtarchie** [pivotal/paving#58]
# Problem

When using `paving`, we would like to disable certain resources that are not needed.
For example, if we are just deploying PKS, we'd like to able to squash the PAS related resources. Or vice versa.
This may go against the original "no switches" guideline of repos directive.

# Proposed Solution

We think there is a way to not have a `terraform` variable switch.
Introducing a scoping of these resources, so they easy for a human to remove and trim.

Organizing the resources by a scoping of `pks` and `pas` can help with that.
For example, a resource named `load_balancer` for PAS, would be named `pas_load_balancer`.
This way someone could just go through the resource and remove all `pas_*` resources.

This organization could also happen at the file level, too.
For example, `lbs.tf` could be split into two different files, `pks_lbs.tf` and `pas_lbs.tf`.
That way entire resources related to PAS could be deleted by doing a `rm pas_*.tf`.

# Known Issue

* How do we solve the issue with `stable_config`?
   The `stable_config` currently references values of the resources that are created.
   If we provide an easy way to moved the resource (see Proposed Solution) then the `stable_config` becomes invalid.

   Possible solution(s):
   * We could provide `pas_stable_config` and `pks_stable_config`, so they are scoped.
   * Within `stable_config` we could scope the values to `pas_` and `pks_`, which makes it easy for a human to remove them, line by line.

**Comment by dashaun** [comment]
Another possible solution:
Instead of making a "remove" workflow, switch to an "additive" workflow.

OpsMan by default then optionally add:
- PAS/TAS
- PKS/TKGI
- CPA

Each add would have their own output (stable_config/stable_config_pas/stable_config_pks/stable_config_cpa)

**Comment by jtarchie** [comment]
I am trying to capture some work in this [branch](https://github.com/pivotal/paving/tree/namespace-resources). My first attempt with AWS shows that the resources have just been pull out into namespace filenames. There is no separate outputs, yet.

**Comment by jtarchie** [comment]
In the current branch, the resources have been split by namespace (`pks`, `pas`, etc) and their outputs.
When I run this through a pipeline that only needs an OpsManager, it exposed that the `ci/configuration` files assume a certain shape of the outputs, too.

For example, the `director.yml` has information about the PKS subnet.

<img width="1259" alt="Screen Shot 2020-08-11 at 11 02 55 AM" src="https://user-images.githubusercontent.com/75184/89926489-36ef1d00-dbc2-11ea-9c26-f6b0466e6b0e.png">

There are many missing values because this pipeline assumed the only stable output needed would be for OpsManager.

Should we use ops-files for the `director.yml` here?

**Comment by jtarchie** [comment]
I've pulled out the PAS and PKS specific values into a their own ops-files for the `director.yml`.
This way people can _opt-in_ to them.

I've tested these AWS changes against an OpsManager only pipeline and the CPA pipeline. It checks out.

**Comment by jtarchie** [comment]
I'll be submitting the same changes for azure, gcp, and NSXT.
Now that there is a pattern and pipelines to test against it.

**Comment by jtarchie** [comment]
This did not work as well as I thought for AWS. I ran a pipeline that removed the `pas-*` and `pks-*` terraform templates. These [lines](https://github.com/pivotal/paving/blob/7754c91c089cf2493c1e0bb383aca43c82916280/aws/ops-manager.tf#L96-L98) affected the pipeline and failed. I don't know how to refactor these components.

**Comment by jtarchie** [comment]
Resolved in accepted PR.
v2.0.0 is out!
