### ISSUE TITLE
Security group and PKS load balancer configuration

### ISSUE THREAD

**Issue by sjmiller609** [pivotal/paving#65]
There may be an issue with routing through the PKS load balancer to the TKGI API. AWS BOSH in ops manager accepts the security group 'platform-vms', which allows ingress from the private network only https://docs.pivotal.io/ops-manager/2-10/aws/config-terraform.html. This is the SG that is applied to the TKGI API VM. In this terraform, there is a security group and load balancer created for that VM aws_security_group.pks-api-lb and aws_lb.pks-api. However, since this load balancer is of type "network" this security group is not applied to this load balancer. The load balancer can be hooked up to the TGKI api just fine, and health checks pass, but this does not allow a client to connect to the TKGI API through the load balancer, because it is blocked by the security group on the instance (there is no security group on the network load balancer). I worked around this issue by concatenating the variable 'ops_manager_allowed_ips' to the allowed ingress CIDR blocks in the security group aws_security_group.platform

```
 cidr_blocks = concat([aws_vpc.vpc.cidr_block], var.ops_manager_allowed_ips)
```

I think maybe this terraform should include another, similar variable called "platform_allowed_ips" or something, or adjust to use application load balancer, but I think that option will be complicated involving certificates.

This may not be an issue if this is the intended behavior, but it does not seem right if the network load balancer is internet-facing to only allow ingress from the private network.

**Comment by jaristiz** [comment]
Hi @sjmiller609 

This issue was addressed on the latest upgrade, please review it and let us know if we missed something.

Regards,
