### ISSUE TITLE
Choice of EC2 instance for OpsManager

### ISSUE THREAD

**Issue by jbogie-vmware** [pivotal/paving#66]
It would be really nice to save some money by being able to choose the instance type used for the OpsManager on AWS.

Older Terraform based repos allowed for the variable "ops_manager_instance_type" to be set.

**Comment by sbogar-shs** [comment]
Hi jbogie, these terraform scripts don't actually create the opsman instance, that gets done by the om process and the instance type can be set in the opsman-config.yml file

see the deploy the director section
docs.pivotal.io/p-concourse/v6/installation/install-platform-automation/
