### ISSUE TITLE
warning for deprecated version property in provider

### ISSUE THREAD

**Issue by sbogar-shs** [pivotal/paving#68]
Warning: Version constraints inside provider configuration blocks are deprecated

  on provider.tf line 2, in provider "aws":
   2:   version    = "~> 2.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

**Comment by jaristiz** [comment]
This work is planned to be tackled when we upgrade to `terraform v1.0`

**Comment by jaristiz** [comment]
Hi @sbogar-shs 

This problem is now fixed with the upgrade to `v.3.0.0` of this repository.

Regards,
